# -*- mode: dockerfile -*-
FROM debian:testing
RUN apt-get update
## Just download/unpack first
RUN apt-get install -y wget xz-utils tar
RUN wget https://cran.r-project.org/src/base-prerelease/R-patched.tar.xz
RUN tar xf R-patched.tar.xz
## Install other packages here to speed up adding/removing these
RUN apt-get install -y file\
   texlive-science texlive-latex-extra texlive-fonts-extra texlive-bibtex-extra\
   ghostscript qpdf tidy\
   libv8-dev\
   make
WORKDIR /R-patched
## Configure stuff
RUN apt-get install -y gcc bison byacc pkgconf gfortran g++\
   libz-dev libbz2-dev liblzma-dev libdeflate-dev\
   libpcre2-dev libcurl4-openssl-dev libxml2-dev\
   cmake
RUN apt-get install -y tcl-dev tk-dev dpkg-dev
RUN ./configure --with-readline=no --with-x=no --with-readline=no\
   --with-tcltk
RUN make -j $(cat /proc/cpuinfo | grep "core id" | sort | uniq | wc -l) &&\
   make install
## Package stuff
WORKDIR /
COPY packages.R .
RUN echo "options(repos=c(CRAN='https://cran.r-project.org'))" >.Rprofile
## Copy the original package ('pkg' context) as folder 'pkg'
COPY --from=pkg . pkg/
## Install packages for the package
RUN Rscript packages.R pkg/
RUN Rscript -e "install.packages(c('VGAM'))"
COPY docker/build-check .
CMD ["bash"]
